version: 3.4

services:
    localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
        - "4566-4599:4566-4599"
        - "${PORT_WEB_UI-8055}:${PORT_WEB_UI-8055}"
    environment:
        - SERVICES=s3
        - AWS_DEFAULT_REGION=us-east-1
    volumes:
        - ./docker/files/test.txt:/home/test.txt
        - ./docker/files/init-s3-bucket.sh:/docker-entrypoint-initaws.d/init-s3-bucket.sh
